[package]
name = "explorer"
# We don't use versioning in the in this crate.
# Please check the `mix.exs` file at the root of this project for the current version.
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "explorer"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
chrono = "0.4"
chrono-tz = "0.9"
rand = { version = "0.8", features = ["alloc"] }
rand_pcg = "0.3"
rustler = { version = "0.34.0" }
thiserror = "1"
either = "1"

# Deps necessary for cloud features.
tokio = { version = "1.35", default-features = false, features = [
  "rt",
], optional = true }
tokio-util = { version = "0.7", default-features = false, features = [
  "io",
  "io-util",
], optional = true }
object_store = { version = "0.10", default-features = false, optional = true }
talib = "0.1.0"
talib-sys = "0.1.0"

# MiMalloc won´t compile on Windows with the GCC compiler.
# On Linux with Musl it won´t load correctly.
[target.'cfg(not(any(all(windows, target_env = "gnu"), all(target_os = "linux", target_env = "musl"))))'.dependencies]
mimalloc = { version = "*", default-features = false }

[dependencies.polars]
version = "0.42"
default-features = false
features = [
  "abs",
  "checked_arithmetic",
  "concat_str",
  "cov",
  "cross_join",
  "csv",
  "cum_agg",
  "cutqcut",
  "decompress-fast",
  "describe",
  "dtype-full",
  "ewma",
  "extract_groups",
  "extract_jsonpath",
  "ipc_streaming",
  "ipc",
  "is_in",
  "lazy",
  "log",
  "mode",
  "moment",
  "parquet",
  "peaks",
  "performant",
  "pivot",
  "product",
  "propagate_nans",
  "random",
  "range",
  "rank",
  "regex",
  "rolling_window",
  "round_series",
  "rows",
  "simd",
  "sql",
  "streaming",
  "strings",
  "temporal",
  "timezones",
  "to_dummies",
  "trigonometry"
]

[dependencies.polars-ops]
version = "0.42"
features = ["abs", "ewma", "cum_agg", "cov"]

[features]
default = ["ndjson", "cloud", "nif_version_2_15"]

cloud = [
  "object_store",
  "tokio",
  "tokio-util",
  "aws",
  "polars/cloud",
  "polars/cloud_write",
]
ndjson = ["polars/json"]
aws = ["object_store/aws", "polars/async", "polars/aws"]

# Feature necessary for Rustler Precompiled.
nif_version_2_15 = ["rustler/nif_version_2_15"]
